# Format: RequestClass=ResponseClass:field_request_1=field_response_1,field_request_2=field_response_2
[DEFAULT]
CreateUserRequest=AdminUserResponse:username=username,role=role
LoginUserRequest=LoginUserResponse:username=username
TransferRequest=TransferResponse:senderAccountId,receiverAccountId,amount
DepositRequest=DepositResponse:id=id
CreateAccountResponse=CreateAccountResponse:id=id,accountNumber=accountNumber,balance=balance
